#done: Argumentos - [args]
#done: Subprocess.Popen - [popen]
#done: Procesos - [fork]
#done: Procesos - [fork_fd]
#done: Procesos - [pipe]
#done: Sincronizacion y shm con mmap - [mmap_sig]
#done: Rot13 con multiprocessing - [mp_rot13]
#done: Calculo matricial - [matriz_pool]
#done: Rot13 con threading - [th_rot13]
Remote shell [serversocket]
Remote shell [remoteshell_ipv6]
#done: Remote shell [remote_shell_asyncio]
Calculo matricial [celery]