#done: Argumentos - [args]
#done: Subprocess.Popen - [popen]
#done: Procesos - [fork]
#done: Procesos - [fork_fd]
Procesos - [pipe]
Sincronizacion y shm con mmap - [mmap_sig]
Rot13 con multiprocessing - [mp_rot13]
Calculo matricial - [matriz_pool]